version: 2
jobs:
    build:
        working_directory: ~/repo
        docker:
            - image: circleci/node:lts
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                  name: install
                  command: yarn install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: test
                command: yarn test
